-- MySQL Script generated by MySQL Workbench
-- Wed Oct 19 20:47:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP DATABASE IF EXISTS deliberridb;
SET GLOBAL FOREIGN_KEY_CHECKS=0;

-- -----------------------------------------------------
-- Schema deliberridb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deliberridb
-- -----------------------------------------------------
CREATE DATABASE  deliberridb;
USE deliberridb ;

-- -----------------------------------------------------
-- Table deliberridb.category
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS deliberridb.category (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL);


-- -----------------------------------------------------
-- Table deliberridb.products
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS deliberridb.products (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(45) NULL,
  price DECIMAL NULL,
  image VARCHAR(45) NULL,
  description VARCHAR(45) NULL,
  promotion INT NULL,
  category_id INT NOT NULL,
    FOREIGN KEY (category_id)
    REFERENCES deliberridb.category (id)
  );


-- -----------------------------------------------------
-- Table deliberridb.users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS deliberridb.users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NULL,
  lastName VARCHAR(45) NULL,
  user VARCHAR(45) NULL,
  email VARCHAR(45) NULL,
  password INT NULL,
  birthDate DATE NULL,
  nationality VARCHAR(45) NULL,
  interestCategory VARCHAR(45) NULL,
  avatar VARCHAR(80) NULL,
  isAdmin VARCHAR(45) NULL
 );